### PR TITLE
Fix glTF mesh colors

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This change makes the colors in the color test FBX and glTF models in https://github.com/vircadia/vircadia/issues/957 appear to render consistently. And the glTF models' colors render the same when viewed in Windows' 3D Viewer.

However, the change makes the colors in the FBX and glTF palm tree models in https://github.com/vircadia/vircadia/issues/302 render very differently.

Testing needed!

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-3ebfe50-_a26f11a8.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-3ebfe50-.tar_a26f11a8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-3ebfe50-.tar_a26f11a8.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-3ebfe50-_a26f11a8.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-Quest-Alpha-PR1181-3ebfe50_a26f11a8.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-3ebfe50_a26f11a8.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-3ebfe50-_a26f11a8.exe

**Comment by SilverfishVR** [comment]
Testing PR1181-3ebfe50

The color panels from #957 looks correct to 👍 

As for the palms, I think that is material related, the fbx palm is fully metallic whereas the glb one is not at all, it is well known issue the fbx models with no metallic map uses the albedo channel instead, maybe no material equals wall white.
Screenshot 2021-04-17 20 05 18
the framebuffer shows metallic value.
left is glb, middle is fbx, and right is same fbx but loaded as non-metal using this fst: https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/vertexColorPanel/fbxPalm_nonMetal.fst and to me it looks the same as glb.

**Comment by Aitolda** [comment]
So it's interesting.  Using Silverfishes method I do indeed get identical looking models, However with a new export for the fbx using   either a solid black texture for metallic I still wind up with a darker color.  So this PR is working perfectly, but we have a problem with blender's metallic export on fbx even when using a texture.  I was under the impression the issue was only when using the slider to set  your metallic.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-f7e04c6-.tar_f67410a5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-f7e04c6-_f67410a5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-f7e04c6-.tar_f67410a5.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-f7e04c6-_f67410a5.dmg

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-Interface-PR1181-f7e04c6-_f67410a5.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-f7e04c6-_f67410a5.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-Quest-Alpha-PR1181-f7e04c6_f67410a5.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1181/Vircadia-PR1181-f7e04c6_f67410a5.apk

**Review by daleglass — APPROVED** [review]

**Pull request merged**
