### PR TITLE
Upgraded Oculus Mobile and Platform SDKs to latest (1.37.0 and 23.0.0)

### PR DESCRIPTION
**Pull request by ArcadeFever**

### CODE REVIEW

**Review by HifiExperiments — APPROVED** [review]

**Review by daleglass — APPROVED** [review]

**Comment by digisomni** [comment]
I realize that these are just for Android and I suppose until more than just Dave can get Android building then we'll have to assume this is moving us closer to success. lol

**Comment by digisomni** [comment]
If this builds correctly and still works for Dave K. then we can consider this mergeable and keep improving on things, hopefully we'll have more people than just Dave being able to compile and run Quest Android. :D

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Alpha-PR919-10586a2_65fb1320.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Alpha-PR919-10586a2.tar_65fb1320.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Alpha-PR919-10586a2_65fb1320.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Alpha-PR919-10586a2.tar_65fb1320.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Alpha-PR919-10586a2_65fb1320.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Quest-Alpha-PR919-10586a2_65fb1320.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR919/Vircadia-Alpha-PR919-10586a2_65fb1320.apk

**Comment by digisomni** [comment]
Builds succeeded. :)

**Pull request merged**
