### PR TITLE
Update Qt 5.15.2 feature branch to 2021.1.0 master

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Testing:
[x] Windows server and Interface.
[x] OSX Interface.

Notes: 
1) OSX Interface may crash on start-up for some people. A call stack / backtrace of such crashes would be most welcome!
2) OSX Interface may crash on shut-down. A fix for this is being developed against the `master` branch.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-PR1058-5fe7fa0.tar_f69e0402.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-PR1058-5fe7fa0_f69e0402.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-PR1058-5fe7fa0.tar_f69e0402.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-PR1058-5fe7fa0_f69e0402.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-Quest-Alpha-PR1058-5fe7fa0_f69e0402.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-PR1058-5fe7fa0_f69e0402.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1058/Vircadia-PR1058-5fe7fa0_f69e0402.exe

**Comment by ctrlaltdavid** [comment]
Downloaded, installed, and ran the Windows PR build OK - Sandbox and Interface.

**Comment by ctrlaltdavid** [comment]
Steve sting on OSX ...
> Crashed on first 2 attempts to launch. Then launched normally every time after that. So I'm going to attribute the 2 crashes to some sort of problem with local user saved data.
> Crashed on quit, every time.
> Performance seems OK (running around The Hub, Hayashi, Rantar Desert)

Crash on launch: Will be pursued as a separate issue after this PR is merged into the Qt feature branch.
Crash on quit: Expected behaviour. Is addressed in https://github.com/vircadia/vircadia/pull/1064

**Comment by ctrlaltdavid** [comment]
Kalila also briefly tried it out.

**Pull request merged**
