### PR TITLE
Enable WebRTC connections to be made to the domain, i.e., add Web client support.

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Enables browser clients using the Web SDK to connect to the domain server and assignment clients via WebRTC.

image

WebRTC connections can be enabled/disabled in the server settings. An SSL certificate is required if running a public domain - the Web client needs to be served via HTTPS in order for Web audio to work, which means that the WebSocket used to establish the WebRTC connection with the domain server also needs to be SSL. (If running on localhost or local network, the Web client can be served via HTTP and Web audio will still work, and no SSL cert is required.)

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1458/Vircadia-Interface-PR1458-d97d8e0-_66fe21e4.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1458/Vircadia-PR1458-d97d8e0-_66fe21e4.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1458/Vircadia-PR1458-d97d8e0-.tar_66fe21e4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1458/Vircadia-PR1458-d97d8e0-.tar_66fe21e4.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1458/Vircadia-PR1458-d97d8e0-_66fe21e4.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1458/Vircadia-PR1458-d97d8e0-_66fe21e4.exe

**Comment by ksuprynowicz** [comment]
Linux version of the server works perfectly combined with native interface on Windows and Linux and also with Web SDK. CPU usage bug doesn't appear either.

**Comment by ksuprynowicz** [comment]
Windows server version still crashes. Connecting from Web SDK, and then umnuting microphone, muting it again and reloading the tab causes crash. Linux version seems to work well. We were not able to crash it.

**Comment by ctrlaltdavid** [comment]
Closed in favour of https://github.com/vircadia/vircadia/pull/1467 and subsequent new PR to merge `webapp` branch into `master`.

**Pull request closed without merging**
