### PR TITLE
Fix settings (QML) spin box stepping

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes spin boxes stepping in values of 1.0 instead of the desired values.
Fixes incorrect stepping due to rounding errors.
Adjusts step sizes and decimal places of some spin boxes.

Settings > General:
- X, Y input: changed number of decimals from 1 to 0.
Settings > Controls:
- Camera sensitivity: stepping fixed (step size 0.1); min value fixed (0.01 -> 0.1), number of decimals changed from 2 to 1.
- Analog++ walk speed: changed number of decimals from 2 to 0.
- User real height: changed number of decimals from 3 to 2; changed step size from 1.0 to 0.01.

Known issues that won't be address in this PR include:
- Can't use spinbox up/down arrows in last couple of items in controls settings dialog in VR: https://github.com/vircadia/vircadia/issues/1157
- "Reset" buttons in slider preferences don't work as expected: https://github.com/vircadia/vircadia/issues/1158
- Settings spin boxes don't properly support use of "," as decimal separator per locale: https://github.com/vircadia/vircadia/issues/1159

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-PR1161-744c66f-_f0eb6a3f.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-PR1161-744c66f-_f0eb6a3f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-PR1161-744c66f-.tar_f0eb6a3f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-PR1161-744c66f-.tar_f0eb6a3f.Z

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-Quest-Alpha-PR1161-744c66f_f0eb6a3f.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-PR1161-744c66f_f0eb6a3f.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1161/Vircadia-PR1161-744c66f-_f0eb6a3f.exe

**Review by JulianGro — APPROVED** [review]
Took me quite some time to understand everything, but everything looks good.
My understanding is that the real fix is the previously missing `realStepSize: preference.step`, while the other changes are just improvements to the code and the spin box settings.

**Comment by Basinsky** [comment]
Spinboxes stepping works. The only thing that is still not working smoothly for me is entering User real-world height. This is not due to the spinbox but has to do with localisation so is for another issue.

**Comment by ctrlaltdavid** [comment]
Localization of QML spinboxes is issue https://github.com/vircadia/vircadia/issues/1159 .

**Comment by ctrlaltdavid** [comment]
Just need to test both desktop and VR, then this PR can be merged.

**Review by digisomni — APPROVED** [review]
Seems to work alright on desktop.

**Pull request merged**
