### PR TITLE
Rename "HifiSockAddr" to "SockAddr"

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-Interface-PR1283-01e6c55-_6a17143d.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-PR1283-01e6c55-.tar_6a17143d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-PR1283-01e6c55-_6a17143d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-PR1283-01e6c55-.tar_6a17143d.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-PR1283-01e6c55-_6a17143d.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-Quest-Alpha-PR1283-01e6c55_6a17143d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-PR1283-01e6c55_6a17143d.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1283/Vircadia-PR1283-01e6c55-_6a17143d.exe

**Comment by daleglass** [comment]
Why though? And "SockAddr" might be a bit too generic and collide with something else at some point.

**Comment by ctrlaltdavid** [comment]
Why? The name "HifiSockAddr" comes through in the Web SDK code and docs owing to the strategy of using the same identifier names for things in the JavaScript as the C++ so that code searches find relevant code in both places.
It doesn't collide with anything at present.

**Comment by digisomni** [comment]
It can be "VircadiaSockAddr" but unsure if that's needed.

**Comment by ctrlaltdavid** [comment]
"VircadiaSockAddr" seems like a ponderously long name. "VrcdSockAddr" would be shorter. But then the question would be, should we add "Vrcd" (or "Vircadia") to a bunch of other names? There's no shortage of names that might conceivably clash sometime in the future.

The Web SDK developer doc TOC:
image

**Comment by digisomni** [comment]
I'm not entirely sure what the reason for doing "HifiSockAddr" was in the first place since SockAddr isn't in use. Was it to make it obvious this was a "High Fidelity" specific type of thingy?

**Comment by daleglass** [comment]
> Why? The name "HifiSockAddr" comes through in the Web SDK code and docs owing to the strategy of using the same identifier names for things in the JavaScript as the C++ so that code searches find relevant code in both places.
> It doesn't collide with anything at present.

Ah, that makes sense. I was just wondering why bother with it, and "SockAddr" sounds generic enough that some library might have one.

**Review by digisomni — APPROVED** [review]

**Pull request merged**
