### PR TITLE
Load serverless tutorial from local disk

### PR DESCRIPTION
**Pull request by SilverfishVR**
fixes https://github.com/vircadia/vircadia/issues/1015

also:
* new mirror and controls poster model.
* moved controls poster so it would not be obscured by the wizzard.
* updated landing point.
* ambient music volume raised a bit, we may want to have a in-worrld toggle for this later https://github.com/vircadia/vircadia/issues/1016.
* turned the zone light up a bit so it is not so dark when on low graphic settings.

### CODE REVIEW

**Comment by JulianGro** [comment]
If it's on disk anyways, it would make a lot more sense to bake the assets. That way they should load a lot faster, especially on low end CPUs.

**Comment by daleglass** [comment]
This is also a lot of binary stuff to put in the repo. How about we download it from S3 instead, at install time?

I think the HiFi installer did that, so the code for it should be already there.

**Comment by SilverfishVR** [comment]
I did not think that size would be an issue considering the resources folder alone is already 10x bigger than what I added. It does still have some textures in there that are not needed as they are already embedded so I could probably remove 6-8MB.

I think the serverless always loaded from network  but the server downloads something, not sure what though.

baking is an option but there is really not a lot in there so if loading that is an issue, you are already in for a bad day if you go through the Hub portal

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-a463d6e-_005dac9c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-a463d6e-.tar_005dac9c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-a463d6e-.tar_005dac9c.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-a463d6e-_005dac9c.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-a463d6e_005dac9c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-Quest-Alpha-PR1142-a463d6e_005dac9c.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-a463d6e-_005dac9c.exe

**Comment by SilverfishVR** [comment]
Does not work, the content is not copied to the `resources\serverless` folder. No idea why.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-863567e-_8434e4ea.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-863567e-.tar_8434e4ea.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-863567e-.tar_8434e4ea.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-863567e-_8434e4ea.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-863567e-_8434e4ea.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-Quest-Alpha-PR1142-863567e_8434e4ea.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1142/Vircadia-PR1142-863567e_8434e4ea.apk

**Comment by SilverfishVR** [comment]
Ok, now it works

**Comment by ArcadeFever** [comment]
Tested on Mac/OSX.  Note, the startup "welcome to vircadia" card is not infront of the new screen.
Screen Shot 2021-04-08 at 5 41 31 PM

Also, the instructions are still low res for Mac/OSX (this has been an outstanding bug, not related to this PR).
Screen Shot 2021-04-08 at 5 13 36 PM

**Comment by SilverfishVR** [comment]
The controls screen was moved so as to not be obscured by the wizard, it(the wizard) should be right in front of you as you spawn in.

It does look a bit out of place, floating there in free air so maybe the concept could be improved with an actual panel holding it?

the blurry issue could be solved in a very hacky way by making that a web panel also, but it is really just a band aid, not a solution.

**Comment by ctrlaltdavid** [comment]
Added issue to make the set-up panel remember its "completed" state: https://github.com/vircadia/vircadia/issues/1179

**Comment by digisomni** [comment]
Needs one tester on Windows and if it's working then, I'll merge it, thank you!

**Review by digisomni — APPROVED** [review]
Worked fine for me on Windows!

**Pull request merged**
