### PR TITLE
Create app: Script indicator toggles for both entity client & server scripts.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
In the Entity List, there is a column to indicate the presence of script on an entity.
_Before that modification, it was only present for entities having a Client Script._
**Now** it will be present if there is a **Client OR Server** script.
image

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-Interface-PR1444-73deee8-_e109b202.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.gz

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.gz

**Comment by SilverfishVR** [comment]
Why no Windows build?

**Comment by digisomni** [comment]
Looks like there was a connection issue with dependencies, maybe it'll work this time.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-Interface-PR1444-73deee8-_e109b202.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.gz

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-_e109b202.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1444/Vircadia-PR1444-73deee8-.tar_e109b202.gz

**Comment by Aitolda** [comment]
Seems to be working. As far as I'm concerned we're ready to merge, but no doubt someone else will want to take a look.

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by ksuprynowicz** [comment]
I tested it on Linux and everything seems to work as intended.

**Pull request merged**
