### PR TITLE
Add "Talk" link to "Help" menu.

### PR DESCRIPTION
**Pull request by digisomni**

### CODE REVIEW

**Review by daleglass — APPROVED** [review]

**Comment by daleglass** [comment]
In the previous dev meeting there were alternative suggestions for how to call this. "Community support", perhaps? "Talk" doesn't seem to be very clear.

**Comment by daleglass** [comment]
There's a syntax error in Menu.cpp

**Comment by digisomni** [comment]
Yeah, I just don't know what I changed to break it.

**Comment by digisomni** [comment]
Okay, I think I got it this time.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1288/Vircadia-Interface-PR1288-9010878-_4b6d1e47.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1288/Vircadia-PR1288-9010878-_4b6d1e47.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1288/Vircadia-PR1288-9010878-.tar_4b6d1e47.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1288/Vircadia-PR1288-9010878-.tar_4b6d1e47.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1288/Vircadia-PR1288-9010878-_4b6d1e47.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1288/Vircadia-PR1288-9010878-_4b6d1e47.exe

**Review by daleglass — APPROVED** [review]

**Pull request merged**
