### PR TITLE
Native client library avatar mixer APIs.

### PR DESCRIPTION
**Pull request by namark**
- [x] New library strictly for handling avatar network packets.
- [x] API functions based on the new library.
- [x] API unit tests.
- [x] API documentation.
- [ ] ~Existing client and server code reworked to make use of the new library.~

This does not include APIs for avatar entities, since those require serialization code from entities library that will be included in a separate PR.

Most of the code is copied from the `libraries/avatars` to `libraries/avatars-core`, with some changes to allow reuse in client library, mainly using CRTP. There are a number of `FIXME: CRTP` comments left with code snippets to aid the reintegration of the new templates into the existing codebase as the final step of refactoring. 

To summarize:
- `avatars-core/src/AssociatedTraitValues` is identical to `avatars/src/AssociatedTraitValues` and is meant to replace it.
- `avatars-core/src/AvatarLogging` is identical to `avatars/src/AvatarLogging` and is meant to replace it.

- `avatars-core/src/AvatarDataStream` is meant to become a base class of `avatars/src/AvatarData`, handling de/serialization of network packets and sending of client's avatar packets. It is a base of `vircadia-client/src/internal/avatars/AvatarData`.
`AvatarData.h` moved to `AvatarDataStream.h` stripped down and turned into a template.
`AvatarData.cpp` moved to `AvatarDataStream.hpp` for the template implementation with modifications and to `AvatarDataStream.cpp` for a few non template functions without modifications.
 
- `avatars-core/src/AvatarPackedHandler` is meant to become a base class of `avatars/src/AvatarHashMap` handling the reception of network packets. It is a base of `vircadia-client/src/internal/avatars/AvatarManager`.
`AvatarHashMap.h` moved to `AvatarPacketHandler.h` and turned into a template.
`AvatarHashMap.cpp` moved to `AvatarPacketHandler.hpp` with modifications.

- `avatars-core/src/ClientTraitsHandler` is meant to become a base of `avatars/src/ClientTraitsHandler`. The code is identical just templated on avatar pointer type. It is a base of `vircadia-client/src/internal/avatars/ClientTraitsHandler`.
`ClientTraitsHandler.h` moved and turned into a template. 
`ClientTraitsHandler.cpp` moved to `ClientTraitsHandler.hpp` with template definitions, the actual implementation code is unchanged.

- `avatars-core/src/AvatarTraits` is a replacement for `avatars/src/AvatarTraits`.
`AvatarTraits.h` moved and turned some function turned into templates.
`AvatarTraits.cpp` moved to `AvatarTraits.hpp` for the templated parts and `AvatarTraits.cpp` for non templated parts, without modification to the actual implementation.

The unit tests are not comprehensive, but they cover the basic functionality (name, model URL, bounds, position, rotation, scale and joints) and can be extended further as other use cases come up.

Instructions for building the client library and running it's tests: https://github.com/vircadia/vircadia/tree/unity-sdk/libraries/vircadia-client. For full test coverage there should be a server running on localhost. Also the avatar tests consist of two parts, sender and receiver that should ran in parallel with `ctest -j4`.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-46f5b3e-.tar_d99838f3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-46f5b3e-_d99838f3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-46f5b3e-.tar_d99838f3.Z

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-46f5b3e-_d99838f3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-46f5b3e-.tar_d99838f3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-46f5b3e-.tar_d99838f3.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-_be18c535.exe

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-.tar_be18c535.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-.tar_be18c535.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-_be18c535.sh

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-.tar_be18c535.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-_be18c535.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-edc7426-.tar_be18c535.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-618980f-.tar_18361bb3.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-618980f-_18361bb3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-618980f-.tar_18361bb3.gz

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-618980f-_18361bb3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-618980f-.tar_18361bb3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-618980f-.tar_18361bb3.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-c0bf3a6-.tar_753b27d8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-c0bf3a6-_753b27d8.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-c0bf3a6-.tar_753b27d8.gz

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-c0bf3a6-.tar_753b27d8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-c0bf3a6-.tar_753b27d8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-c0bf3a6-_753b27d8.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-ff26390-_22fbf37e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-ff26390-.tar_22fbf37e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-ff26390-.tar_22fbf37e.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-.tar_0d2ac065.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-_0d2ac065.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-.tar_0d2ac065.gz

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-_0d2ac065.dmg

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-_0d2ac065.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-_0d2ac065.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-.tar_0d2ac065.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-e5a5ce8-.tar_0d2ac065.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-Interface-PR1655-fe442ff-_ec8919f4.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-_ec8919f4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-.tar_ec8919f4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-.tar_ec8919f4.gz

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-_ec8919f4.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-.tar_ec8919f4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-.tar_ec8919f4.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-fe442ff-_ec8919f4.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-b601138-.tar_80382691.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-b601138-.tar_80382691.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-b601138-_80382691.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-_a64c53b3.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-.tar_a64c53b3.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-.tar_a64c53b3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-_a64c53b3.sh

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-_a64c53b3.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-.tar_a64c53b3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-_a64c53b3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0a38483-.tar_a64c53b3.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-Interface-PR1655-cc9bcc2-_7582c54e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-.tar_7582c54e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-.tar_7582c54e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-_7582c54e.sh

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-_7582c54e.exe

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-_7582c54e.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-.tar_7582c54e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-_7582c54e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-cc9bcc2-.tar_7582c54e.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8b211fb-.tar_a35731f2.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8b211fb-_a35731f2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8b211fb-.tar_a35731f2.Z

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8b211fb-.tar_a35731f2.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8b211fb-_a35731f2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8b211fb-.tar_a35731f2.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-98cec86-.tar_8a0e48c8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-98cec86-.tar_8a0e48c8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-98cec86-_8a0e48c8.sh

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-98cec86-_8a0e48c8.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-98cec86-.tar_8a0e48c8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-98cec86-.tar_8a0e48c8.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-_e0650eb9.sh

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-_e0650eb9.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-_e0650eb9.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-Interface-PR1655-0d5b0b5-_e0650eb9.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-_e0650eb9.sh

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-_e0650eb9.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-_e0650eb9.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-0d5b0b5-.tar_e0650eb9.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-Interface-PR1655-0d5b0b5-_e0650eb9.dmg

**Comment by digisomni** [comment]
QA consists of running the new unit tests and also testing avatars on a Domain with the native Interface.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-Interface-PR1655-414c7a1-_e0246477.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-.tar_e0246477.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-_e0246477.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-.tar_e0246477.Z

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-_e0246477.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-.tar_e0246477.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-_e0246477.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-414c7a1-.tar_e0246477.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-.tar_3d7e219f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-.tar_3d7e219f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-_3d7e219f.sh

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-_3d7e219f.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-.tar_3d7e219f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-_3d7e219f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-8be5528-.tar_3d7e219f.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-.tar_6025143e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-.tar_6025143e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-_6025143e.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-_6025143e.dmg

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-_6025143e.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-_6025143e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-.tar_6025143e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1655/Vircadia-PR1655-4314cb6-.tar_6025143e.gz

**Pull request closed without merging**
