### PR TITLE
Add appreciate app as default app.

### LINKED ISSUE #963: Make Appreciate app a default app
Title says it all. It helps for when we have events and such for people to be able to easily express appreciation. :)

### PR DESCRIPTION
**Pull request by digisomni**
Closes #963

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-df70cc7_407d436e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-df70cc7.tar_407d436e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-df70cc7.tar_407d436e.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-df70cc7_407d436e.dmg

**Comment by ctrlaltdavid** [comment]
Are the files just a copy as-is from somewhere (hifi-content repo?) or have there also been some changes made?

**Comment by digisomni** [comment]
No changes whatsoever. Direct copy from vircadia-content. :)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-1b597c7_407d436e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-1b597c7.tar_407d436e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-1b597c7.tar_407d436e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-1b597c7_407d436e.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-1b597c7_407d436e.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Quest-Alpha-PR974-1b597c7_407d436e.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-1b597c7_407d436e.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-e33b17d.tar_08652769.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-e33b17d_08652769.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-e33b17d.tar_08652769.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-e33b17d_08652769.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Quest-Alpha-PR974-e33b17d_08652769.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-e33b17d_08652769.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR974/Vircadia-Alpha-PR974-e33b17d_08652769.exe

**Comment by ctrlaltdavid** [comment]
Noted: Includes a new resource JSON file.

**Comment by digisomni** [comment]
Yes, includes a resource.json file and emojis... are probably still broken. They've been broken. However, there is no indication that they even exist in the app so no one will consider it a bug.

I figure we can just merge this if it works as is (no need to CR the entire app! lol) to get everyone clappin', and improve later as needed. :)

**Pull request merged**
