### PR TITLE
Add UI for setting metaverse server URL.

### PR DESCRIPTION
**Pull request by namark**
This is https://github.com/vircadia/vircadia/pull/1174 merged with https://github.com/overte-org/overte/pull/2 with some improvements.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-_07fcf66d.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-.tar_07fcf66d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-.tar_07fcf66d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-_07fcf66d.sh

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-Interface-PR1586-c297112-_07fcf66d.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-.tar_07fcf66d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-.tar_07fcf66d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-_07fcf66d.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-c297112-_07fcf66d.exe

**Review by daleglass — APPROVED** [review]

**Comment by digisomni** [comment]
Awaiting some slight UX changes from Namark.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-_e7147f7f.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-Interface-PR1586-dc2b8c4-_e7147f7f.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-.tar_e7147f7f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-_e7147f7f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-.tar_e7147f7f.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-_e7147f7f.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-_e7147f7f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-.tar_e7147f7f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1586/Vircadia-PR1586-dc2b8c4-.tar_e7147f7f.gz

**Review by digisomni — APPROVED** [review]
Works fine for me, thanks!

**Review by daleglass — APPROVED** [review]

**Pull request merged**
