### PR TITLE
Make build system more robust and add IPFS gateway support.

### PR DESCRIPTION
**Pull request by namark**
as an alternative to the Amazon S3 bucket, which is now used as a fallback by default. 

The external build asset configuration is centralized in the cmake/ExternalAssetConfig.cmake file.

The EXTERNAL_BUILD_ASSETS CMake parameter has been replaced with EXTERNAL_BUILD_ASSETS_DIRECT_BASE_URLS, which is a list of base URLs that will be tried in order.

New parameters:
EXTERNAL_BUILD_ASSETS_IPFS_BASE_URLS - a list of IPFS gateway URLs (including /ipfs endpoint) that will be tried in order.
USE_IPFS_EXTERNAL_BUILD_ASSETS - use IPFS gateways to download external build assets (default: true)
USE_DIRECT_EXTERNAL_BUILD_ASSETS  - use the direct download links as a fallback (default: true)

Based on https://github.com/vircadia/vircadia/pull/1572.
Minor conflict with https://github.com/vircadia/vircadia/pull/1558.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-e6ce351-_10f991d8.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-Interface-PR1573-957880e-_10f991d8.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-957880e-_10f991d8.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-47c4f2f-.tar_e323a420.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-47c4f2f-_e323a420.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-47c4f2f-.tar_e323a420.Z

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-Interface-PR1573-47c4f2f-_e323a420.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-47c4f2f-_e323a420.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-47c4f2f-_e323a420.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-_deda990b.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-.tar_deda990b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-_deda990b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-.tar_deda990b.gz

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-Interface-PR1573-ab36b7b-_deda990b.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-_deda990b.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-.tar_deda990b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-.tar_deda990b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1573/Vircadia-PR1573-ab36b7b-_deda990b.sh

**Comment by mrkcdf** [comment]
Cmake changes reviewed. No issues identified

**Review by digisomni — APPROVED** [review]

**Pull request merged**
