### PR TITLE
Update OpenVR to 1.16.8.

### PR DESCRIPTION
**Pull request by digisomni**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1322/Vircadia-Interface-PR1322-966311c-_bfa10852.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1322/Vircadia-PR1322-966311c-_bfa10852.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1322/Vircadia-PR1322-966311c-.tar_bfa10852.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1322/Vircadia-PR1322-966311c-_bfa10852.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1322/Vircadia-PR1322-966311c-.tar_bfa10852.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1322/Vircadia-PR1322-966311c-_bfa10852.exe

**Comment by AleziaKurdis** [comment]
Just tried this build... 
Vr Compositor is still behaving as a memory black hole.

image

**Comment by digisomni** [comment]
Even with it still as a memory blackhole, maybe this update can be merged anyway since it is at least an update?

**Comment by digisomni** [comment]
Needs testing for full body tracking.

**Review by daleglass — APPROVED** [review]

**Comment by digisomni** [comment]
Tested by Alezia and Silverfish.

**Pull request merged**
