### PR TITLE
Fix deprecated usage of multiple keys in QHash and QMap.

### PR DESCRIPTION
**Pull request by daleglass**
This replaces those uses with QMultiHash and QMultiMap. This removes a fair amount of warnings. Only 157 to go.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-Interface-PR1468-2147dec-_33ac65cd.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-_33ac65cd.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-.tar_33ac65cd.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-.tar_33ac65cd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-_33ac65cd.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-_33ac65cd.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-.tar_33ac65cd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-_33ac65cd.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-2147dec-.tar_33ac65cd.Z

**Review by HifiExperiments — APPROVED** [review]
hm these white space changes might cause some annoying conflicts with other PRs but otherwise ok

I also wonder if these Maps were actually originally supposed to be Maps or if they were intended to be Hashes

**Comment by daleglass** [comment]
@HifiExperiments Yeah, the space stuff isn't ideal but that's easy enough to fix if anything conflicts. Also makes things a bit less annoying, as it avoids the need to mess with the whitespace by hand.

I think maybe we could just do a giant whitespace tidying commit some day and then install a rule that from now on, it must be perfect.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-_14374d4d.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-Interface-PR1468-39619f3-_14374d4d.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-.tar_14374d4d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-.tar_14374d4d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-_14374d4d.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-_14374d4d.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-_14374d4d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-.tar_14374d4d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1468/Vircadia-PR1468-39619f3-.tar_14374d4d.gz

**Review by digisomni — APPROVED** [review]
The Interface on Windows and macOS runs, the server runs on Windows.

**Pull request merged**
