### PR TITLE
Removed 'Visit in VR' button from server admin GUI

### PR DESCRIPTION
**Pull request by Colorfingers**
This link is an artifact of the old Hifi and is broke... removing from admin GUI to reduce confusion.

### CODE REVIEW

**Comment by namark** [comment]
hmmm, It should be permanently hidden in the latest release with this change https://github.com/vircadia/vircadia/pull/1595

Are you sure it's still there?

**Comment by Colorfingers** [comment]
> hmmm, It should be permanently hidden in the latest release with this change #1595
> 
> Are you sure it's still there?

Why permanently hide it... what function does it provide that needs to be retained?  just curious. A user asked why it was there and Madders suggested we remove it.  I was just being proactive.  I should have done a search... we can delete this pull request if it needs to be retained.

**Comment by namark** [comment]
We want to eventually re-enable it, linking to web interface once that's ready, that's why I kept it. Here is the initial discussion https://github.com/vircadia/vircadia/issues/1591

**Comment by Colorfingers** [comment]
Duplicate effort... Button is being hidden later for reuse.

**Pull request closed without merging**
