### PR TITLE
Fixed empty POST request to settings.json crashing the Domain server.

### PR DESCRIPTION
**Pull request by namark**

### CODE REVIEW

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-e9ea7f1-_7fac5dd8.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-Interface-PR1438-e9ea7f1-_7fac5dd8.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-e9ea7f1-_7fac5dd8.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-e9ea7f1-.tar_7fac5dd8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-e9ea7f1-.tar_7fac5dd8.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-e9ea7f1-_7fac5dd8.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-Interface-PR1438-1606bcd-_7fac5dd8.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-1606bcd-_7fac5dd8.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-1606bcd-_7fac5dd8.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-1606bcd-.tar_7fac5dd8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-1606bcd-.tar_7fac5dd8.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-1606bcd-_7fac5dd8.exe

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-Interface-PR1438-1606bcd-_7fac5dd8.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1438/Vircadia-PR1438-1606bcd-_7fac5dd8.dmg

**Comment by digisomni** [comment]
Worked alright on Windows but I didn't test the actual crash case, just ran the server for a bit.

**Pull request merged**
