### PR TITLE
Domain server ACME client.

### PR DESCRIPTION
**Pull request by namark**
- [x] Adapt the acme-lw library for use in Domain Server 
- [x] ~~Implement http endpoint for acme client configuration~~
- [x] ~~Implement web UI for acme client configuration~~

This PR is basic version of the domain server ACME client that can automatically generate and renew Let's Encrypt certificates. It's based on the a heavily modified fork of the acme-lw library https://github.com/namark/acme-lw, that is set up as a git submodule.

How it works: 
There is a new section in the domain server settings page called SSL ACME Client, where the client can be configured. Most of the fields there can be left untouched as the defaults should work, the only thing that is required is adding at least one domain name in the Domain Names table. With that the client can be enabled and upon restart it will generate and write the account private key (if it does not exist), order the certificate form Let's Encrypt (if it does not exist), complete the challenges, write the retrieved certificate files, and report the expiry date and renewal schedule in server logs. After this the WebRTC and SSL can be enabled in Networking / WebRTC and after another restart everything should work.  
The challenges are complete using http, hosting on port 80 from memory, so it assumes that all the domain names resolve to itself and that the port 80 is available, at least on first order, after that with Let's Encrypt it would not be necessary for 300 days. 
For intensive testing of the certificate generation process the ACME Directory Endpoint should be set to Let's Encrypt's staging API (https://acme-staging-v02.api.letsencrypt.org/directory), to avoid throttling.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-_0d26f548.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-.tar_0d26f548.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-_0d26f548.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-.tar_0d26f548.Z

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-Interface-PR1456-767dbea-_0d26f548.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-_0d26f548.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-.tar_0d26f548.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-_0d26f548.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-767dbea-.tar_0d26f548.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-1734ffd-.tar_16dfa992.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-1734ffd-.tar_16dfa992.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-1734ffd-_16dfa992.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-1734ffd-_16dfa992.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-Interface-PR1456-06ed720-_b7d36370.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-_b7d36370.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-.tar_b7d36370.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-.tar_b7d36370.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-_b7d36370.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-_b7d36370.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-.tar_b7d36370.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-06ed720-.tar_b7d36370.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-.tar_a8841398.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-.tar_a8841398.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-_a8841398.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-_a8841398.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-_a8841398.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-.tar_a8841398.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-582559b-.tar_a8841398.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-_0105f2ae.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-.tar_0105f2ae.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-.tar_0105f2ae.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-_0105f2ae.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-.tar_0105f2ae.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-.tar_0105f2ae.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-8760a3b-_0105f2ae.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-.tar_0c12bc13.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-_0c12bc13.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-.tar_0c12bc13.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-_0c12bc13.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-.tar_0c12bc13.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-.tar_0c12bc13.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-97f8ba5-_0c12bc13.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-_897d475c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-.tar_897d475c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-.tar_897d475c.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-_897d475c.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-.tar_897d475c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-_897d475c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-aed7012-.tar_897d475c.gz

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-Interface-PR1456-eadd476-_897d475c.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-_897d475c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-.tar_897d475c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-_897d475c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-.tar_897d475c.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-_897d475c.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-_897d475c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-.tar_897d475c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-eadd476-.tar_897d475c.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-Interface-PR1456-55f0360-_d26aaddd.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-.tar_d26aaddd.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-_d26aaddd.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-.tar_d26aaddd.gz

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-_d26aaddd.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-_d26aaddd.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-.tar_d26aaddd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-_d26aaddd.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1456/Vircadia-PR1456-55f0360-.tar_d26aaddd.Z

**Comment by namark** [comment]
Closing in favor of https://github.com/vircadia/vircadia/pull/1540

**Pull request closed without merging**
