### PR TITLE
Update to Qt 5.15.2

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Changes:
[x] Update Windows to Qt 5.15.2 and OpenSSL 1.1.1h
[x] Update OSX to Qt 5.15.2 - Dave K.
[x] Update Linux to Qt 5.15.2 - Moto.
[ ] Update Android to Qt 5.15.2 - In progress [Dave K.] May be done in a separate PR, post-merge.
[ ] Address Qt build warnings - Will probably be done in a separate PR, post-merge.

Also: 
- The QtSpeech module is now included.,

Bugs:
[-] OSX crash on start-up for some people. https://github.com/vircadia/vircadia/issues/1072 ... This hasn't really been recurring.

To do when merged:
[ ] Prepare and upload the Qt symbols for Sentry. See the instructions for each OS in /tools/qt-builder/README.md.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-90b43b1.tar_d5530f18.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-90b43b1_d5530f18.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-90b43b1.tar_d5530f18.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-90b43b1_d5530f18.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-90b43b1_d5530f18.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-90b43b1_d5530f18.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-d4a43ea_c66f6a1a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-d4a43ea.tar_c66f6a1a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-d4a43ea_c66f6a1a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-d4a43ea.tar_c66f6a1a.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-d4a43ea_c66f6a1a.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-d4a43ea_c66f6a1a.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Alpha-PR938-d4a43ea_c66f6a1a.apk

**Comment by digisomni** [comment]
Would it be best to CR now and then CR again for each merge into the branch or would it be best to do it all at the end? Mayhaps all at the end to save time...

**Comment by HifiExperiments** [comment]
I think android will also need to be updated

**Comment by ArcadeFever** [comment]
> 
> 
> I think android will also need to be updated

Working on it, but I don't want to hold back the other updates if I can't figure it out soonish.

**Comment by ArcadeFever** [comment]
@ctrlaltdavid can you post your Qt configure output?  I want to compare to my OSX configure to make sure I didn't miss any other features during compile.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-3452a43-.tar_d7f7acec.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-3452a43-_d7f7acec.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-3452a43-.tar_d7f7acec.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-3452a43-_d7f7acec.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-3452a43_d7f7acec.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-3452a43_d7f7acec.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-3452a43-_d7f7acec.exe

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-354f674-_3961d9d3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-354f674-.tar_3961d9d3.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-354f674-.tar_3961d9d3.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-354f674-_3961d9d3.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-354f674-_3961d9d3.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-354f674_3961d9d3.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-354f674_3961d9d3.apk

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-cf0a0cb-_3961d9d3.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-cf0a0cb-.tar_3961d9d3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-cf0a0cb-_3961d9d3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-cf0a0cb-.tar_3961d9d3.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-cf0a0cb-_3961d9d3.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-cf0a0cb_3961d9d3.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-cf0a0cb_3961d9d3.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-6fec039-.tar_5b18b1f1.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-6fec039-.tar_5b18b1f1.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-6fec039-_5b18b1f1.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-6fec039-_5b18b1f1.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-6fec039_5b18b1f1.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-6fec039_5b18b1f1.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-6fec039-_5b18b1f1.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-b21694e-_1cadfcc2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-b21694e-.tar_1cadfcc2.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-b21694e-.tar_1cadfcc2.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-b21694e-_1cadfcc2.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-b21694e_1cadfcc2.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-Quest-Alpha-PR938-b21694e_1cadfcc2.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR938/Vircadia-PR938-b21694e-_1cadfcc2.exe

**Comment by ctrlaltdavid** [comment]
Kalila has reported that doing the following crashes people on 2021.1.1 but not on the PR:
- Web entity.
- Change the user agent in the Web entity.
- Cache-bust the Web entity (e.g., add `?12345` to the URL).

**Review by daleglass — APPROVED** [review]

**Comment by ctrlaltdavid** [comment]
Created the following issues for downstream work:
- #1189 
- #1190 
- #1191

**Pull request merged**
