### PR TITLE
Update WebRTC Windows package

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Updates the WebRTC version used on Windows from version M81 to M84.
- Adds WebRTC data channel to the WebRTC VCPKG. *

`*` In current `master`, the audio component of WebRTC is used for echo cancellation.

### Testing	

Check that the following audio features continue to work on Windows:
- [x] Echo cancellation
- [x] Noise reduction
- [x] Manual nose reduction

Check that other OSes continue to work:
- [ ] Linux server
- [x] Linux client
- [x] MacOS client

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-Interface-PR1221-bb13814-_ce31b70a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-bb13814-.tar_ce31b70a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-bb13814-.tar_ce31b70a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-bb13814-_ce31b70a.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-bb13814-_ce31b70a.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-bb13814-_ce31b70a.exe

**Comment by JulianGro** [comment]
Some questions:
Why are we enabling proprietary codecs?
Why are we disabling libaom?

We aren't allowing proprietary codecs on Qt-Webengine, and my understanding is that disabling libaom will disable the future use of the AV1 video format (not that it could be used in Vircadia right now, or will be supported in the near future)

**Comment by ctrlaltdavid** [comment]
The audio part(s) of WebRTC is currently used in `master` for the echo cancellation feature. This PR isn't changing the audio/video components enabled/disabled - it is just adding WebRTC peer-to-peer data channel that isn't included in the current WebRTC VCPKG.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-Interface-PR1221-9bc0655-_ce31b70a.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-9bc0655-_ce31b70a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-9bc0655-.tar_ce31b70a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-9bc0655-.tar_ce31b70a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-9bc0655-_ce31b70a.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-9bc0655-_ce31b70a.exe

**Review by digisomni — APPROVED** [review]
The audio seems to work well for the client and server on Windows for the specified test cases.

**Comment by ArcadeFever** [comment]
Testing Mac client build, and all is well.

**Review by JulianGro — APPROVED** [review]
Tested the Linux client, and everything in terms of audio seems to work okay still.

**Comment by JulianGro** [comment]
Test server is running at 49.12.68.54
Not sure if it makes much sense for me to test it alone.

**Comment by digisomni** [comment]
Testing so far...

2021.1.2 Windows native Interface -> PR 1221 Linux Server = Wearables not allowed notification does not pop up.
PR 1221 Windows native Interface -> PR 1221 Windows Server = Wearables not allowed notification **does** show.

**Comment by JulianGro** [comment]
> Testing so far...
> 
> 2021.1.2 Windows native Interface -> PR 1221 Linux Server = Wearables not allowed notification does not pop up.
> PR 1221 Windows native Interface -> PR 1221 Windows Server = Wearables not allowed notification **does** show.

I just checked the config and "Avatar entitites" are indeed allowed for everyone. Did you disable them for this test and re-enable them afterwards?

**Comment by digisomni** [comment]
> 
> 
> > Testing so far...
> > 2021.1.2 Windows native Interface -> PR 1221 Linux Server = Wearables not allowed notification does not pop up.
> > PR 1221 Windows native Interface -> PR 1221 Windows Server = Wearables not allowed notification **does** show.
> 
> I just checked the config and "Avatar entitites" are indeed allowed for everyone. Did you disable them for this test and re-enable them afterwards?

I only disabled them to see if the pop-up would show up. My intent is to see if the pop-up would show because that's a packet trade happening where the domain is notifying my interface that I won't be allowed to have avatar entities if I join.

Further testing... 

So I tried to wear wearables on your test server and it did not work for me on 2021.1.2 and on PR 1221 for Windows.

However, on my Windows PR 1221 server wearing / blocking with notice for wearables works with 2021.1.2 and PR 1221 for Windows.

Do you have my username or a permission somewhere unchecking the avatar entities? Mayhaps for another permission other than "everyone"? Logging out did not allow me to have wearables either.

Your server is blocking my wearables on PR 1221's Windows native Interface even. And it also does not notify me before joining.

**Comment by ctrlaltdavid** [comment]
This PR shouldn't have any effect on wearables or permissions: it just updates the WebRTC VCPKG used on Windows, per the description. I've updated the PR to the latest master to make it easier to compare behaviour against master, and so also master against 2021.1.2.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-Interface-PR1221-7022cd8-_5e1537e1.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-7022cd8-.tar_5e1537e1.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-7022cd8-.tar_5e1537e1.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-7022cd8-_5e1537e1.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-7022cd8-_5e1537e1.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-Quest-Alpha-PR1221-7022cd8_5e1537e1.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-7022cd8_5e1537e1.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1221/Vircadia-PR1221-7022cd8-_5e1537e1.exe

**Pull request closed without merging**
