### PR TITLE
Housekeeping: use of std::make_shared / QSharedPointer::create.

### PR DESCRIPTION
**Pull request by odysseus654**
This was a code review of all uses of the "new" keyword when constructing a std::shared_ptr or QSharedPointer object:

(1) convert to make_shared / QSharedPointer::create if possible/appropriate.  This ensured that:
- there was less "gap" between construction of the raw pointer and the construction of the shared pointer object.
- There is less ability to specify a different pointer type between the object and the pointer
- the STL spec apparently ensures that the pointer and object are constructed within a single memory allocator, so this saves another trip to the heap allocator.

make_shared cannot be used when:
- there is a custom deleter (there may be value in factoring out a common building object that uses QObject::deleteLater though)
- the constructor is not public or otherwise inaccessible to the template function

(2) Where make_shared / QSharedPointer could not be used, ensure that the shared pointer is *initially* constructed with the actual datatype of the object
- This is mostly for the standard deleter, otherwise destructing a base class depends on virtual destructors being setup properly and potentially could cause potential memory leaks.  I noticed the plugin code did this a *lot*
- When using a custom deleter... might have value? unsure so much

There is likely at least some code changes that would take effect with this code, most likely:
- allocation differences (make_shared doing in-place construction), and
- the delete operation will be deleting the object as the type it was constructed (rather than any base class)

Testing focus:
- Check for any change in behavior or persistent memory usage on shutdown or recycling? There may be *slight* changes in behavior for:
- - "Dynamic" assignment client startup/shutdown (whatever this is)
- - "Controller conditional routing"
- - HiFi codec plugin
- - Neuron input plugin
- - Osc input plugin
- - SDL2 input plugin
- - Oculus display plugin
- - Oculus input plugin
- - OpenVR display plugin
- - Vive input plugin
- - Athena codec plugin
- - PCM codec plugin
- - zLib codec plugin

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-0cef6e0-.tar_05182af5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-0cef6e0-_05182af5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-0cef6e0-.tar_05182af5.Z

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-Interface-PR1339-0cef6e0-_05182af5.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-0cef6e0-_05182af5.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-0cef6e0-_05182af5.exe

**Review by HifiExperiments — APPROVED** [review]
changes look good although I'm a little worried about conflicts with other open PRs, like my TAA PR: https://github.com/vircadia/vircadia/pull/576

won't be hard to resolve but still

**Comment by odysseus654** [comment]
Yah, 1200 and 666 are already out of date, waiting a bit for things to merge more before resolving conflicts.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-Interface-PR1339-4e3db8f-_05182af5.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-_05182af5.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-_05182af5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-.tar_05182af5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-.tar_05182af5.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-_05182af5.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-.tar_05182af5.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-_05182af5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-4e3db8f-.tar_05182af5.gz

**Review by digisomni — APPROVED** [review]
Seemed to work fine for my local server and Interface on Windows 10. Tried with the Valve Index through SteamVR.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-.tar_05182af5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-.tar_05182af5.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-_05182af5.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-_05182af5.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-.tar_05182af5.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-.tar_05182af5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1339/Vircadia-PR1339-ea3a423-_05182af5.sh

**Pull request merged**
