### PR TITLE
Disable z-write for transparent draws

### PR DESCRIPTION
**Pull request by Phil-Palmer**
This PR disables writing to the depth buffer (z-write) when drawing transparent elements (addresses partially https://github.com/vircadia/vircadia/issues/224), in these functions:
`GeometryCache::getSimplePipeline`,
`Procedural::Procedural`,
`GeometryCache::getWebBrowserProgram`,
`ParabolaPointer::RenderState::ParabolaRenderItem::getParabolaPipeline`,
`GeometryCache::useGridPipeline`,
`Font::setupGPU`.

Z-write is controlled by the 'writeMask' parameter of `gpu::State::setDepthTest`.

alpha-zwrite

alpha-zwrite_webpage

### Test plan

https://github.com/vircadia/vircadia/issues/224 describes the bug and how to test it.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-687ba54_90799e10.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-687ba54_90799e10.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-687ba54.tar_90799e10.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-687ba54.tar_90799e10.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-687ba54_90799e10.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-687ba54_90799e10.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Quest-Alpha-PR953-687ba54_90799e10.apk

**Review by HifiExperiments — COMMENTED** [review]
this is great!  thanks for catching this

there are a few other places we could also use this fix:
- ParabolaPointer.cpp line 418 (used for parabolas like the teleport lasers)
- Font.cpp line 279 (used for the text part of text entities)
- GeometryCache.cpp line 2030 (used for grid entities)

I think in all of them, std::get<0>(key) is true for transparent

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-b8da6ca_4f71cb59.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-b8da6ca_4f71cb59.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-b8da6ca.tar_4f71cb59.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-b8da6ca.tar_4f71cb59.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-b8da6ca_4f71cb59.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Quest-Alpha-PR953-b8da6ca_4f71cb59.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-b8da6ca_4f71cb59.apk

**Comment by Phil-Palmer** [comment]
> this is great! thanks for catching this
> 
> there are a few other places we could also use this fix:
> 
> * ParabolaPointer.cpp line 418 (used for parabolas like the teleport lasers)
> * Font.cpp line 279 (used for the text part of text entities)
> * GeometryCache.cpp line 2030 (used for grid entities)
> 
> I think in all of them, std::get<0>(key) is true for transparent

Thanks, I've made these changes in 12095fed96eff31ade799f75863f34e996cd9d8b, but not tested them yet.

**Comment by HifiExperiments** [comment]
@Phil-Palmer sorry, to clarify, we want to use !std::get<0>(key) as the second argument in those three cases, because we set the state for multiple pipelines, some of which are opaque and some of which are transparent

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-f0d73ec_12095fed.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-f0d73ec.tar_12095fed.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-f0d73ec.tar_12095fed.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-f0d73ec_12095fed.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-f0d73ec_12095fed.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Quest-Alpha-PR953-f0d73ec_12095fed.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-f0d73ec_12095fed.exe

**Comment by Phil-Palmer** [comment]
> @Phil-Palmer sorry, to clarify, we want to use !std::get<0>(key) as the second argument in those three cases, because we set the state for multiple pipelines, some of which are opaque and some of which are transparent

Oops yes, thanks, fixed in 0f9117b978333d7ab322be15a631354ec2bf34dd.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-2eab0a4.tar_0f9117b9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-2eab0a4_0f9117b9.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-2eab0a4.tar_0f9117b9.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-2eab0a4_0f9117b9.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-2eab0a4_0f9117b9.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Quest-Alpha-PR953-2eab0a4_0f9117b9.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR953/Vircadia-Alpha-PR953-2eab0a4_0f9117b9.apk

**Review by HifiExperiments — APPROVED** [review]

**Comment by AleziaKurdis** [comment]
**Tested with success:**
image

image

_But testing this I found another issue that was present already in 2020.3.3.RC1
the shape get a bad size when we change the shape. 
(I logged this issue for that: https://github.com/vircadia/vircadia/issues/956 )_

**Comment by SilverfishVR** [comment]
PR953-2eab0a4

I'm, still seeing issues with shapes as in https://github.com/vircadia/vircadia/issues/224:
Screenshot 2021-01-13 001854

could someone load this and see if I'm just being a dummy: [ShapeOclutionTest.json](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/ShapeOclutionTest.json)

**Comment by HifiExperiments** [comment]
I think the problem here might be with how we draw shapes.  for efficiency, we batch together primitive draw calls into one big draw call that renders all shapes of one type as instances.  this drastically improves rendering performance when we have lots of shapes, but it also might be introducing these issues where we aren’t drawing transparent objects of different shapes in the necessary order for alpha blending.  the solution may be to only batch together opaque shapes, and split transparent shapes into their own separate draw calls (they should already be sorted by the time that they are drawn).

**Comment by digisomni** [comment]
image

This is how that test looks on 2020.3.3.

image

And this is how it looks in PR953.

**Comment by SilverfishVR** [comment]
Yes, it does fix something, currently putting a 0.1 opacity quad in front of a 0.9 opacity cube effectively renders a hole in the cube, neat trick but clearly not right, that is fixed, the batching is something for a separate PR I think.

* shapes with opacity < 1 always renders in-front of materials with alpha blending(OPACITY_MAP_BLEND), 
alpha mask(OPACITY_MAP_MASK) works as expected. Could also be due to the Batching issue 🤷‍♂️ 

* My [kittenception](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/kittenception.glb) model still looks really weird but I noticed that it looks the same in blender, so maybe it's normal
(_32 double sided planes in alpha blend mode that, when viewed from the +Z direction, has the sorting reversed, the plane furthest away is on top_)

* for intersecting planes, I still get a destinct swich in rendering order depending on viewing angle, not sure what to expect here.

vircadia-snap-by--on-2021-01-16_18-41-55

* everything else looks right to me 👍

**Pull request merged**
