### PR TITLE
Remove <thread> library from main.cpp.

### PR DESCRIPTION
**Pull request by Penguin-Guru**
Just happened to notice this. I could be wrong, but I did compile and run the interface with no apparent issues.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-Interface-PR1474-7c6395d-_46bf41bf.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-.tar_46bf41bf.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-_46bf41bf.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-.tar_46bf41bf.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-_46bf41bf.exe

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-_46bf41bf.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-.tar_46bf41bf.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-.tar_46bf41bf.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-7c6395d-_46bf41bf.sh

**Review by daleglass — APPROVED** [review]

**Comment by daleglass** [comment]
Looks good, but I think we should do this systematically. There was some sort of tool for this, to check an entire source tree. Might speed up the build some.

**Comment by Penguin-Guru** [comment]
That seems like a useful tool. Where there is one of these unneeded libraries, there are hopefully more. :)

**Comment by digisomni** [comment]
Both the Interface and server were fine on Windows, however I will rebuild with the latest master (includes the WebRTC changes) just to be sure it'll at least build fine.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-.tar_46bf41bf.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-.tar_46bf41bf.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-_46bf41bf.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-_46bf41bf.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-.tar_46bf41bf.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-.tar_46bf41bf.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1474/Vircadia-PR1474-1278c57-_46bf41bf.sh

**Review by digisomni — APPROVED** [review]

**Pull request merged**
