### PR TITLE
Fixed metallic material import for glTF.

### PR DESCRIPTION
**Pull request by ksuprynowicz**
Fixes incorrect handling of "metallicFactor" value on GLTF import.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
I tested it on Linux.
Master build:
vircadia-snap-by-X74hc595-on-2021-12-23_19-54-23

gltf_metallic_fix branch:
vircadia-snap-by-X74hc595-on-2021-12-23_13-42-43

I also compared it with Babylon.js, Three.js and Filament, and it now it works the same way as in these engines.

**Comment by ctrlaltdavid** [comment]
Does this fix the problems in both the following issues?
- https://github.com/vircadia/vircadia/issues/1529
- https://github.com/vircadia/vircadia/issues/909

**Comment by ksuprynowicz** [comment]
> Does this fix the problems in both the following issues?

It does :)

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-.tar_9a3686cc.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-.tar_9a3686cc.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-_9a3686cc.sh

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-Interface-PR1552-b3d0d06-_9a3686cc.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-_9a3686cc.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-.tar_9a3686cc.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-.tar_9a3686cc.gz

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-b3d0d06-_9a3686cc.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-Interface-PR1552-cc71aed-_9a3686cc.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-_9a3686cc.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-.tar_9a3686cc.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-.tar_9a3686cc.gz

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-_9a3686cc.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-_9a3686cc.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-.tar_9a3686cc.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1552/Vircadia-PR1552-cc71aed-.tar_9a3686cc.Z

**Pull request merged**
