### PR TITLE
triggerHapticPulse supports arbitrary device index instead of just two hands

### PR DESCRIPTION
**Pull request by HifiExperiments**
inspired by @daleglass's FOSDEM talk, I've been meaning to change this for a while

Test plan:
- no real functional change
- make sure you can still trigger a haptic pulse on existing hand controllers, for example: `Controller.triggerHapticPulse(0.5, 10, 2);` should trigger a pulse on both hands

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-76640b7_b6e74668.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-76640b7.tar_b6e74668.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-76640b7.tar_b6e74668.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-76640b7_b6e74668.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-76640b7_b6e74668.exe

**Review by daleglass — APPROVED** [review]
Heheh. I like it, but I have to admit my bias :smile:

**Comment by digisomni** [comment]
How come the Android build failed?

**Comment by daleglass** [comment]
Aha:
```
  ../../../../../../../libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp:164:84: error: non-virtual member function marked 'override' hides virtual member function
      bool triggerHapticPulse(float strength, float duration, controller::Hand hand) override;
                                                                                     ^
  ../../../../../../../libraries/controllers/src/controllers/InputDevice.h:121:18: note: hidden overloaded virtual function 'controller::InputDevice::triggerHapticPulse' declared here: type mismatch at 3rd parameter ('uint16_t' (aka 'unsigned short') vs 'controller::Hand')
      virtual bool triggerHapticPulse(float strength, float duration, uint16_t index) { return false; }
                   ^
  ../../../../../../../libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp:480:25: warning: comparison of two values with different enumeration types ('ovrTrackedDeviceTypeId' (aka 'ovrTrackedDeviceTypeId_') and 'ovrHandedness_') [-Wenum-compare]
      auto poseId = (hand == VRAPI_HAND_LEFT) ? controller::LEFT_HAND : controller::RIGHT_HAND;
```

Makes sense, the type of the parameter changed, and the Oculus controller code needs to be updated to match.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-437a66d.tar_a18c2483.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-437a66d_a18c2483.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-437a66d.tar_a18c2483.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-437a66d_a18c2483.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-437a66d_a18c2483.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-Quest-Alpha-PR1013-437a66d_a18c2483.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1013/Vircadia-PR1013-437a66d_a18c2483.apk

**Comment by Aitolda** [comment]
I just tried this on an Oculus Quest via Link (acting as Rift). Assuming I did this correctly (entered the command above in the dev console while holding my controllers in VR) there was no haptic effect whatsoever.

**Comment by HifiExperiments** [comment]
hmmm yeah does that work if you try the same thing on master/the current version on the website?  I’m not sure if haptics are expected to work over link...

**Comment by Aitolda** [comment]
> hmmm yeah does that work if you try the same thing on master/the current version on the website? I’m not sure if haptics are expected to work over link...

Hmm... apparently not.

**Comment by digisomni** [comment]
This did not work for me on the PR or 2020.3.3... I'm using a Valve Index with Index Controllers. I guess it never worked on those?

**Comment by HifiExperiments** [comment]
hmmm maybe my command is just wrong...you could try bumping up the first two numbers?

**Comment by Aitolda** [comment]
> hmmm maybe my command is just wrong...you could try bumping up the first two numbers?

Ok. Tested again. Discovered that it doesn't work IF you have your dashboard (floating desktop overlay) open.  But if I close, that and pretty enter blindly it works.  It's subtle, but it's there.

**Comment by digisomni** [comment]
OK, so trying again... it works (while in VR mode). However, a main problem I've found is that you cannot consistently tell it which hand to use. Both hands works consistently, however specifying 0 or 1 tends to favor 1 pretty much always or it will trigger both. I could not get it to trigger on the left hand only.

**Comment by HifiExperiments** [comment]
what about on master?  there’s not supposed to be any functional change here besides allowing values over 2, so I’m surprised it’s acting so weirdly.

**Comment by digisomni** [comment]
You got me there, on master nothing is working for me. So I guess this is an improvement. :)

**Review by digisomni — APPROVED** [review]

**Comment by digisomni** [comment]
Trying it again on 2021.1.0 it only works for the left hand. Using an index of 0 works, and using an index of 2 works. However 1 does nothing.

It took a good 10 or so seconds to start working though, submitting commands too soon I guess just wasn't going to work.

**Comment by HifiExperiments** [comment]
what device are you using?  the haptic code is pretty old and relatively untouched, I’m wondering if the SDKs we’re using are just too old for newer devices...another reason we should just scrap them all and write an OpenXR plugin 😛

**Comment by digisomni** [comment]
I'm using an Index. The OpenVR SDK was updated to the newest quite recently (past 8 months) so that should also work, heh.

But yes, OpenXR would be ideal, heh. :)

**Pull request merged**
