### PR TITLE
Initial partial linux aarch64 support

### PR DESCRIPTION
**Pull request by JulianGro**
This PR adds unfinished aarch64 support for Vircadia.
I got a server to build and run on Manjaro ARM, but haven't been able to polish enough to build on Ubuntu 18.04.
I didn't want to release anything until I got Continuos Integration but my repo has been getting older and older making it harder and harder to work with master.
If anyone wants to tinker with an aarch64 Vircadia server on anything newer than Ubuntu 18.04, this is the PR for that.

I intend to try to finish getting the openSUSE Build Service to work before polishing aarch64 support up properly, since GitHub Actions only supports Ubuntu and most aarch64 systems will be using Debian.

Since this is still very experimental, I left the packages on my server.

To build with vircadia-builder you just do what you always do with vircadia-builder which is using the repo and tag that this PR is coming from. An example command would be `./vircadia-builder -r https://github.com/JulianGro/project-athena.git -t initial_linux_aarch64`.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-PR1163-ddfd724-_69a3f21e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-PR1163-ddfd724-.tar_69a3f21e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-PR1163-ddfd724-.tar_69a3f21e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-PR1163-ddfd724-_69a3f21e.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-Quest-Alpha-PR1163-ddfd724_69a3f21e.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-PR1163-ddfd724_69a3f21e.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1163/Vircadia-PR1163-ddfd724-_69a3f21e.exe

**Comment by daleglass** [comment]
What do you mean by "my repo has been getting older and older making it harder and harder to work with master"?

**Review by daleglass — APPROVED** [review]

**Comment by JulianGro** [comment]
> What do you mean by "my repo has been getting older and older making it harder and harder to work with master"?

I opened this PR at 4am so that was just very inaccurate. It just gets harder to manage the changes with all my experimental aarch64 branches gathering dust on my machine. Getting some of this into master makes the list of changes smaller.

**Comment by digisomni** [comment]
Will test on Windows to make sure nothing breaks. @daleglass will test on Linux. :)

**Review by digisomni — APPROVED** [review]
Dale tested on Linux and I ran CMake on Windows, both worked.

**Pull request merged**
