### PR TITLE
Remove "Console" options from Interface-only installer (Windows)

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
The advanced tab of the Windows Interface-only installer had three "console" advanced install options. These related to a cut-down version of the Sandbox's Windows system tray icon, with options (e.g., "GoTo") the currently don't work properly.

This PR temporarily removes the three "console" options from the Interface-only advanced install options and no longer creates a "Console" start menu item - until such time as the "console" is fixed (and perhaps renamed) or it's decided that it should be removed permanently. See issue: https://github.com/kasenvr/project-athena/issues/683

Note: The Console is still installed - just the same as if only "Interface" is enabled for installation in the combined Interface+Sandbox installer.

Also:
- Renames the installer build instructions from INSTALL.md to INSTALLER.md.
- Fixes use of the BYPASS_SIGNING flag, used for bypassing the signing of Windows production builds.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

#### 1) Interface-only and Interface + Sandbox installers

Build 2 installers:
- Interface-only
- Interface + Sandbox
Note: You can do `set BYPASS_SIGNING=1` to set an environment variable to bypass signing the installers.

Test Interface-only installer:
- Express install works:
  - Installs Interface.
  - Doesn't install domain server - domain-server.exe is not present in the install directory.
  - Interface runs.
- Custom install works:
  - There are no "Console" checkbox items present in the advanced options.
  - Installs Interface.
  - Doesn't install domain server - domain-server.exe is not present in the install directory.
  - Interface runs.

Test Interface + Sandbox installer:
- The 3 "Sandbox" checkbox items are present.
- Express install works as expected.
- Custom install works as expected. In parficular, the Sandbox server is installed or not installed, and run or not run, per checkbox items.


#### 2) Signed production build

Check that a signed release-for-production build can still be built.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-b109d73_857bf7de.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-b109d73.tar_857bf7de.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-b109d73.tar_857bf7de.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-b109d73_857bf7de.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-b109d73_857bf7de.exe

**Comment by kasenvr** [comment]
Made a PR installer only build and indeed a shortcut was created even though on the custom install section there was no option (Which is good) for that. Also a server-console folder with a server-console.exe is present in the install directory, it does run, though there is no domain-server so it doesn't exactly do much...

image

**Comment by ctrlaltdavid** [comment]
Yes, it has the same behaviour as installing only Interface from combined Interface+Sandbox installer. Whether or not the Console app should be called something else, have its current Interface-only items (and fix their operation), or perhaps not be installed in Interface-only installations is a separate issue, I think. This PR is just addressing the need for Interface-only installer not having a confusing "Console" option - to make it easier for the likes of Steve to guide end users in set-up.

**Comment by kasenvr** [comment]
> 
> 
> Yes, it has the same behaviour as installing only Interface from combined Interface+Sandbox installer. Whether or not the Console app should be called something else, have its current Interface-only items (and fix their operation), or perhaps not be installed in Interface-only installations is a separate issue, I think. This PR is just addressing the need for Interface-only installer not having a confusing "Console" option - to make it easier for the likes of Steve to guide end users in set-up.

That works pretty well I expect, the only thing I can think of is does that shortcut show up in the Interface-Only build on MacOS? That's the part that gets people. :)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-9abbf73.tar_f523416f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-9abbf73_f523416f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-9abbf73.tar_f523416f.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-9abbf73_f523416f.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR824/Vircadia-Alpha-PR824-9abbf73_f523416f.exe

**Comment by kasenvr** [comment]
I gave it a test on Mac and I still see it.
image
I used the parameter `-DCLIENT_ONLY=1`

**Comment by ctrlaltdavid** [comment]
Did you install over the top or do a clean install?

What is the screen shot showing exactly? I.e., what is the Windows equivalent?
The  Console is still build and installed on Windows, but the Console is not prompted about during installation and no Console items are created in the Start Menu or on the desktop.

**Comment by ctrlaltdavid** [comment]
The problematic "Console" icon probably comes about when generating the DMG, though I've not been able to see where this icons are generated. (I don't use Mac, which doesn't help.) Note also the lower-case "i" in "interface".

**Comment by kasenvr** [comment]
Let's try and get "interface" to say "Vircadia" and merge this as is. :)

**Review by digisomni — APPROVED** [review]
Seems to be working fine on Windows for me.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Alpha-PR824-8ef5418_71cee734.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Alpha-PR824-8ef5418.tar_71cee734.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Alpha-PR824-8ef5418.tar_71cee734.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Alpha-PR824-8ef5418_71cee734.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Alpha-PR824-8ef5418_71cee734.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Quest-Alpha-PR824-8ef5418_71cee734.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR824/Vircadia-Alpha-PR824-8ef5418_71cee734.exe

**Pull request merged**
