### PR TITLE
Create App - "Add All Zones" on renderWithZones selector.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR adds a "**Add All Zones**" button to the Multiple Zones Selector component (used for "renderWithZones")

image

**This addresses issue #775**

That PR also contains a small bug fix for the "**Broken Url Report**" for the error 0.
Previously it was referring to "_Url not well formed_" (which wasn't exact for all the possible causes)
Now it will displays "_Server not found_".

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-.tar_43bf840b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-_43bf840b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-.tar_43bf840b.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-_43bf840b.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-_43bf840b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-.tar_43bf840b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-482319e-.tar_43bf840b.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-_13897a38.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-.tar_13897a38.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-.tar_13897a38.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-_13897a38.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-.tar_13897a38.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-_13897a38.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1519/Vircadia-PR1519-95c52aa-.tar_13897a38.gz

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by Aitolda** [comment]
Works as expected. However maybe a suggestion for a future update would be that new dropdown menu would let you select multiple zones by holding control and selecting, or hold shift and selecting so everything in between is selected.  Then press add zones and all selected would be added, but also include a "select all" option.  Thoughts?

**Comment by AleziaKurdis** [comment]
> Works as expected. However maybe a suggestion for a future update would be that new dropdown menu would let you select multiple zones by holding control and selecting, or hold shift and selecting so everything in between is selected. Then press add zones and all selected would be added, but also include a "select all" option just like the entity list. Thoughts?

HMD make this a bit complicated.
That would need a full refactor since this is actually a list of buttons. 
But I keep that in mind.
Let's use this for a 6 months and re-evaluate.

**Comment by Aitolda** [comment]
> Let's use this for a 6 months and re-evaluate.

Yeah. I see no need to dive into additional changes now.  This is a solid PR already.

**Pull request merged**
