### PR TITLE
Specify macOS SDK to 10.12 on GHA to solve crash when entering fullscreen.

### PR DESCRIPTION
**Pull request by JulianGro**
This PR works around the known MacOSX SDK bug
Fixes https://github.com/vircadia/vircadia/issues/994

While I don't for sure know if this is actually the same issue, I am closing this as well. If it happens again someone can just reopen it.
Closes https://github.com/vircadia/vircadia/issues/695

~~I have yet to test this myself yet actually, since I cannot upload to the S3 from my own repo.~~
The fix works for me on Catalina with AMD graphics.

### CODE REVIEW

**Comment by digisomni** [comment]
Can we add a comment in there explaining that we use the 10.12 SDK due to a bug in OpenGL on macOS?

**Comment by JulianGro** [comment]
@daleglass I took the liberty of hosting the SDK on the S3, since you need to download and extract a 10GiB file to get it directly from Apple (which I did to get this SDK).

I actually wanted to add a checksum check as well, but shasum on macOS is bugged and only allows checking SHA1 (at least on High Sierra).

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-Interface-PR1411-56286a1-_a7731cf4.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-56286a1-.tar_a7731cf4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-56286a1-.tar_a7731cf4.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-56286a1-_a7731cf4.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-56286a1-_a7731cf4.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-56286a1-_a7731cf4.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-.tar_38e56b97.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-_38e56b97.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-.tar_38e56b97.gz

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-Interface-PR1411-26fbd1f-_38e56b97.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-_38e56b97.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-_38e56b97.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-.tar_38e56b97.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-_38e56b97.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-26fbd1f-.tar_38e56b97.Z

**Comment by digisomni** [comment]
I think this should wait until it can get it hosted on IPFS or similar. I realize that GitHub also does not like its hosting being used for distribution cases, but maybe we can use that (linking to the raw URL) in the meantime because in reality this is a build step and GitHub is **very** often used for pulling files and folders during builds as far as I know.

**Comment by digisomni** [comment]
https://cloudflare-ipfs.com/ipfs/QmdNLMCUCw8hBTqinkc7ke88WgRb7M2mWQbccQPDsyaub8?filename=MacOSX10.12.sdk.tar.xz/

Does this link work for others? If so, it would be best if others also pin it to help increase its uptime and general performance.

**Comment by JulianGro** [comment]
> Does this link work for others? If so, it would be best if others also pin it to help increase its uptime and general performance.
It ends with an underscore when I download it. Other than that it seems to work.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-_1a82c646.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-.tar_1a82c646.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-_1a82c646.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-.tar_1a82c646.gz

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-Interface-PR1411-682c8fb-_1a82c646.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-_1a82c646.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-.tar_1a82c646.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-_1a82c646.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-682c8fb-.tar_1a82c646.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-Interface-PR1411-88aee5c-_e9b4f0bd.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-_e9b4f0bd.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-.tar_e9b4f0bd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-.tar_e9b4f0bd.Z

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-_e9b4f0bd.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-_e9b4f0bd.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-.tar_e9b4f0bd.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-.tar_e9b4f0bd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1411/Vircadia-PR1411-88aee5c-_e9b4f0bd.sh

**Review by digisomni — APPROVED** [review]

**Pull request merged**
