### PR TITLE
Fix nvtt on x86

### LINKED ISSUE #862: nvtt (nvidia-texture-tools) fails to compile on Fedora 33: fatal error: sys/sysctl.h: No such file or directory
This is a bit of an odd one. It compiled on Fedora 31 and 32, on 33 it fails with this:

```
/usr/lib64/ccache/c++  -I/home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed56c2-ae979c4acf/src -Isrc -I/home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src    /70a4ed56c2-ae979c4acf/extern/poshlib -I/home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed56c2-ae979c4acf/extern/stb -I/home/dale/Vircadia/vcpkg/bd824a32/bui    ldtrees/nvtt/src/70a4ed56c2-ae979c4acf/src/nvthread -fPIC -march=athlon64 -fPIC -g -fPIC -std=gnu++11 -MD -MT src/nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o -MF src/    nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o.d -o src/nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o -c /home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed    56c2-ae979c4acf/src/nvthread/nvthread.cpp
 16 /home/dale/Vircadia/vcpkg/bd824a32/buildtrees/nvtt/src/70a4ed56c2-ae979c4acf/src/nvthread/nvthread.cpp:14:10: fatal error: sys/sysctl.h: No such file or directory
 17    14 | #include <sys/sysctl.h>
 18       |          ^~~~~~~~~~~~~~
```

Indeed there's no such file, the correct one would be:

    #include <linux/sysctl.h>

 Looking at the latest nvtt code shows a change has been made to address this:

https://github.com/castano/nvidia-texture-tools/blob/248f84ca465ab15a5d5c23d97cb90c74633b38cb/src/nvthread/nvthread.cpp#L12

It could be time to upgrade our NVTT source to a more recent version.

### PR DESCRIPTION
**Pull request by daleglass**
This uses a repository at https://github.com/vircadia/nvidia-texture-tools with the existing patches already integrated into it, and an additional fix on top.

See https://github.com/vircadia/nvidia-texture-tools/commit/26b65cd105f0d2f425b5152b460a8d5eaa44b514 for the change.

Testing:

* Build on X86
* Build on ARM

Fixes #862

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1255/Vircadia-PR1255-2d1121b-.tar_0c8201b2.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1255/Vircadia-PR1255-2d1121b-_0c8201b2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1255/Vircadia-PR1255-2d1121b-.tar_0c8201b2.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1255/Vircadia-PR1255-2d1121b-_0c8201b2.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1255/Vircadia-PR1255-2d1121b_0c8201b2.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1255/Vircadia-Quest-Alpha-PR1255-2d1121b_0c8201b2.apk

**Review by JulianGro — APPROVED** [review]
All changes are already on upstream. (Even that last one https://github.com/castano/nvidia-texture-tools/pull/328/files )
Except for the last one, the changes seem to work on aarch64. (I never tested that last commit on aarch64)

**Comment by daleglass** [comment]
> All changes are already on upstream. (Even that last one https://github.com/castano/nvidia-texture-tools/pull/328/files )
> Except for the last one, the changes seem to work on aarch64. (I never tested that last commit on aarch64)

I don't think that change is quite right actually, since according to the docs, `va_end` invalidates the va_list. And `va_arg` modifies it, so I suppose technically the safe thing to do would be to make a copy every time in the loop, or refactor the code.

But then I figure, it's probably safe to ignore that since it's some kind of debug function anyway we probably never end up calling, and the project is dead at any rate.

I considered using newer code, but hifi's changes don't apply cleanly.

It looks like nvtt isn't used that much in the code, so it doesn't seem to be worthwhile to spend any more time on this than strictly necessary. The next step would be just finding a replacement lib.

**Comment by JulianGro** [comment]
Specifically needs a test on Linux.
shocktail39 built with the patches that are included in the nvtt repo now and their build was unable to bake any textures.
unknown
Prebaked textures like in the Hub do show up fine.

**Comment by shocktail39** [comment]
https://user-images.githubusercontent.com/6035079/123890752-c958f600-d925-11eb-883e-aa67859db617.mp4

hello.  adding onto this, i just noticed that my avatar icon doesn't seem to show up either when compiling locally.  in the attached video, the one with the grey walls is the appimage downloaded from the website, and the one with the white walls is my self-built copy.  the avatar URLs are identical, but only the appimage is showing my thumbnail.

**Comment by shocktail39** [comment]
ok, so turns out i'm a moron and this whole thing was a me problem.  my system qt wasn't built with jpeg support.  i rebuilt it with that, and now everything works great.

**Comment by JulianGro** [comment]
https://github.com/vircadia/vircadia/issues/1087

**Review by digisomni — APPROVED** [review]
Works for me on Windows.

**Review by digisomni — APPROVED** [review]

**Pull request merged**
