### PR TITLE
Domain server first time wizard improvements and fixes.

### PR DESCRIPTION
**Pull request by namark**
Resolves https://github.com/vircadia/vircadia/issues/1551 and https://github.com/vircadia/vircadia/issues/1419
Includes the relevant dependable PRs.

There are a few caveats with 1419. I tried to use quasars [fixed positioning](https://v0-14.quasar-framework.org/components/fixed-positioning-on-layout.html) for the checkbox, but it wouldn't work no matter where I put it, so I eventually went with just basic css. I also had to dig into internals of [vanta](https://github.com/tengbao/vanta) to implement pausing of the animation. I though to open a PR there, but not sure if the project is still alive, we might need to fork or completely replace it in the long term.

### CODE REVIEW

**Comment by digisomni** [comment]
image

image

For some reason this is coming back in a stringified form now?

**Comment by namark** [comment]
Probably this issue https://github.com/axios/axios/issues/4018, will try bumping axios version further I guess

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.gz

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-Interface-PR1603-362de54-_bef80c20.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-Interface-PR1603-362de54-_bef80c20.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.gz

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-Interface-PR1603-362de54-_bef80c20.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.gz

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-.tar_bef80c20.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-362de54-_bef80c20.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-863d2ff-_30ccad20.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-Interface-PR1603-863d2ff-_30ccad20.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-863d2ff-_30ccad20.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-863d2ff-.tar_30ccad20.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-863d2ff-.tar_30ccad20.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1603/Vircadia-PR1603-863d2ff-_30ccad20.exe

**Review by digisomni — APPROVED** [review]
Looks good to me.

**Pull request merged**
