### PR TITLE
Rename to "Vircadia Server" and disable server shortcuts with Express install on Windows

### PR DESCRIPTION
**Pull request by digisomni**
To test, download a PR build and let it perform an express install... you should not have any shortcuts for the server console or "Vircadia Server" for that PR.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-3fa22cc-.tar_c9ab2a68.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-3fa22cc-_c9ab2a68.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-3fa22cc-.tar_c9ab2a68.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-3fa22cc-_c9ab2a68.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-3fa22cc_c9ab2a68.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-Quest-Alpha-PR1081-3fa22cc_c9ab2a68.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d5b5f16-.tar_fe3f0069.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d5b5f16-_fe3f0069.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d5b5f16-.tar_fe3f0069.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d5b5f16-_fe3f0069.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d5b5f16-_fe3f0069.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-Quest-Alpha-PR1081-d5b5f16_fe3f0069.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d5b5f16_fe3f0069.apk

**Comment by Aitolda** [comment]
Shortcuts no, but worth pointing out that when you open the installed server in the toolbar, it still presents the option to "visit sandbox.

**Comment by Steve-Pruneau** [comment]
On macOS this build (1081) is still named "Sandbox.app".

**Comment by digisomni** [comment]
Closes #648

**Comment by ctrlaltdavid** [comment]
"Sandbox" is still referred to in the Windows system tray menu.
image

**Review by ctrlaltdavid — CHANGES_REQUESTED** [review]
Fix Windows system tray mention of "Sandbox".

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d6ef59e-_ecda58dc.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d6ef59e-.tar_ecda58dc.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d6ef59e-_ecda58dc.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d6ef59e-.tar_ecda58dc.gz

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d6ef59e_ecda58dc.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-Quest-Alpha-PR1081-d6ef59e_ecda58dc.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1081/Vircadia-PR1081-d6ef59e-_ecda58dc.exe

**Review by ctrlaltdavid — APPROVED** [review]

**Pull request merged**
