### PR TITLE
Enable WebRTC connections to be made to the Domain, i.e., add Web client support.

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Enables browser clients using the Web SDK to connect to the domain server and assignment clients via WebRTC.

image

WebRTC connections can be enabled/disabled in the server settings. An SSL certificate is required if running a public domain - the Web client needs to be served via HTTPS in order for Web audio to work, which means that the WebSocket used to establish the WebRTC connection with the domain server also needs to be SSL. (If running on localhost or local network, the Web client can be served via HTTP and Web audio will still work, and no SSL cert is required.)

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1469/Vircadia-PR1469-da7a0b7-_8764e6f0.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1469/Vircadia-Interface-PR1469-da7a0b7-_8764e6f0.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1469/Vircadia-PR1469-da7a0b7-.tar_8764e6f0.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1469/Vircadia-PR1469-da7a0b7-_8764e6f0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1469/Vircadia-PR1469-da7a0b7-.tar_8764e6f0.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1469/Vircadia-PR1469-da7a0b7-_8764e6f0.exe

**Review by digisomni — APPROVED** [review]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

Works fine to me with basic local testing between native and web on a local server.

**Comment by ksuprynowicz** [comment]
I tested it with Kalila on Linux server and both native and web clients, and everything, including chat and messages works perfectly.

**Comment by ksuprynowicz** [comment]
Windows server functionality is also tested now and works correcly except for slightly choppy audio from web client.

**Pull request merged**
