### PR TITLE
Try making OSX shut down scripts in the same manner as other OSes - Qt 5.15.2

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Alpha-PR1031-3c4287b_6d0512e9.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Alpha-PR1031-3c4287b.tar_6d0512e9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Alpha-PR1031-3c4287b.tar_6d0512e9.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Alpha-PR1031-3c4287b_6d0512e9.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Quest-Alpha-PR1031-3c4287b_6d0512e9.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Alpha-PR1031-3c4287b_6d0512e9.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1031/Vircadia-Alpha-PR1031-3c4287b_6d0512e9.exe

**Comment by ArcadeFever** [comment]
I tested this many times, and many scenarios, similar to PR build 1032, in which I exist after clicking create to inspect several objects.  I could not get this OSX PR build to crash on exit.

**Comment by Steve-Pruneau** [comment]
Thanks ArcadeFever. PR 1031 for macOS does not seem to crash on Quit. But it crashes on every other start-up. I reproduced this behavior several times.

[1] Double-click the app icon to launch. It will crash and offer the on-screen crash report (attached).
[2] Double-click the app icon again to launch. It offers the dialog whether to use existing settings or start clean. It launches successfully.
[3] Quit as normal. No problems.
[4] Double-click the app icon to launch. It will crash and offer the on-screen crash report (attached).
[5] Double-click the app icon again to launch. It offers the dialog whether to use existing settings or start clean. It launches successfully.

[Viracadia_Interface_macOS_PR1031_crash-on-open.txt](https://github.com/vircadia/vircadia/files/5984031/Viracadia_Interface_macOS_PR1031_crash-on-open.txt)

**Comment by Steve-Pruneau** [comment]
I am running iMac 27 inch. 16gb RAM. macOS Big Sur 11.2.1

**Comment by ctrlaltdavid** [comment]
The start-up crash is probably the same start-up crash that some people have encountered in the OSX Qt 5.15.2 PR, https://github.com/vircadia/vircadia/pull/968 .

**Comment by ctrlaltdavid** [comment]
Closed in favour of https://github.com/vircadia/vircadia/pull/1064

**Pull request closed without merging**
