### PR TITLE
Fix privacy setting text

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Changed two occurrences of "High Fidelity" to "Vircadia".

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-PR1071-901355f-_4a9d4d4c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-PR1071-901355f-_4a9d4d4c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-PR1071-901355f-.tar_4a9d4d4c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-PR1071-901355f-.tar_4a9d4d4c.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-PR1071-901355f-_4a9d4d4c.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-PR1071-901355f_4a9d4d4c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1071/Vircadia-Quest-Alpha-PR1071-901355f_4a9d4d4c.apk

**Review by HifiExperiments — APPROVED** [review]

**Review by daleglass — APPROVED** [review]

**Comment by digisomni** [comment]
Now we just need like 10 testers on this. It could cause rampant crashing, I just know it.

**Comment by daleglass** [comment]
By the way, is this data actually going anywhere? I checked, and it should be sent to the metaverse server, to `/api/v1/user_activities`. Is anything accepting it?

**Comment by digisomni** [comment]
Not that I know of, there's a return statement at the top of the function as well.

**Review by digisomni — APPROVED** [review]
Worked alright for me.

**Pull request merged**
