### PR TITLE
Add "RELEASE_NAME" env variable.

### PR DESCRIPTION
**Pull request by digisomni**
This environment variable gets appended into the Interface title bar so that the release name does not have to be added alongside the `RELEASE_NUMBER`.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c.tar_a0747b29.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c.tar_a0747b29.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c_a0747b29.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c_a0747b29.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c.tar_a0747b29.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c.tar_a0747b29.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c_a0747b29.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-ac8d72c_a0747b29.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-6624c70.tar_a0747b29.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-6624c70_a0747b29.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-6624c70.tar_a0747b29.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-6624c70_a0747b29.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-6624c70_a0747b29.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Quest-Alpha-PR975-6624c70_a0747b29.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-6624c70_a0747b29.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-66c6268.tar_c443a2dd.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-66c6268_c443a2dd.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-66c6268.tar_c443a2dd.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-66c6268_c443a2dd.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-66c6268_c443a2dd.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Alpha-PR975-66c6268_c443a2dd.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR975/Vircadia-Quest-Alpha-PR975-66c6268_c443a2dd.apk

**Review by ctrlaltdavid — APPROVED** [review]

**Pull request merged**
