### PR TITLE
Separate rendering effect settings.

### PR DESCRIPTION
**Pull request by Penguin-Guru**
This is a work in progress, but potentially useful.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
I just tested it on Windows and it works as intended. Sadly individual disabling of rendering effects is not possible for now except shadows - this would probably need to be exposed to scripting engine.

**Comment by Penguin-Guru** [comment]
I don't think it would be very difficult to extend the functionality to other effects, but I could be wrong. Either way, I don't plan to do it right now. Maybe later.

**Comment by ksuprynowicz** [comment]
> 
> 
> I don't think it would be very difficult to extend the functionality to other effects, but I could be wrong. Either way, I don't plan to do it right now. Maybe later.

Wouldn't it be necessary to expose them to scripting engine first?

**Comment by Penguin-Guru** [comment]
Not necessary, but desirable. The scripting engine's interface doesn't seem too complicated. :)

**Comment by Aitolda** [comment]
Same results as ksuprynowicz. It separates as expected but rendering effects other than shadows cannot be disabled separately.

**Comment by Penguin-Guru** [comment]
> Same results as ksuprynowicz. It separates as expected but rendering effects other than shadows cannot be disabled separately.

That is the intended design right now. Shadows were easier and more important to separate. The currently disabled checkboxes are place-holders so those settings can be implemented and the U.I. is more intuitive/consistent.

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1423/Vircadia-PR1423-d340a86-.tar_ca4a817d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1423/Vircadia-PR1423-d340a86-.tar_ca4a817d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1423/Vircadia-PR1423-d340a86-_ca4a817d.sh

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1423/Vircadia-Interface-PR1423-d340a86-_ca4a817d.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1423/Vircadia-PR1423-d340a86-_ca4a817d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1423/Vircadia-PR1423-d340a86-_ca4a817d.exe

**Pull request merged**
