### PR TITLE
Possible fix for script related crashes

### PR DESCRIPTION
**Pull request by HifiExperiments**
each ScriptEngine runs in its own thread.  I *think* that sometimes a script will stop (why?  idk) and its ScriptEngine will be deleted while the workerThread is still running, causing the crash.  adding this waitTillDoneRunning call should theoretically prevent that.  it will have the side effect of holding up the thread...but I don't think it can block the main thread?

Test plan:
- test running a variety of local scripts and entity scripts.  they should behave as expected, and you shouldn't crash

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-a477f15_c7b5854d.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-a477f15_c7b5854d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-a477f15.tar_c7b5854d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-a477f15.tar_c7b5854d.Z

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-a477f15_c7b5854d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-Quest-Alpha-PR1054-a477f15_c7b5854d.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-a477f15_c7b5854d.exe

**Comment by digisomni** [comment]
I'll run this as my build for a little while and see if anything changes. :)

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-b2dc4ca.tar_c7b5854d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-b2dc4ca_c7b5854d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-b2dc4ca.tar_c7b5854d.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-b2dc4ca_c7b5854d.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-b2dc4ca_c7b5854d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-Quest-Alpha-PR1054-b2dc4ca_c7b5854d.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-b2dc4ca_c7b5854d.exe

**Comment by digisomni** [comment]
I'm running it, I haven't been using the Create app too much yet and I have crashed at least once. However, things don't seem to be worse, so that at least works.

Will report back with further results once I use the Create app more.

**Comment by HifiExperiments** [comment]
ok so that was wrong, waitTillDoneRunning can't stop the thread because ~ScriptEngine is called on the thread it lives on...it has this at the top:

```
    if (workerThread == QThread::currentThread()) {
        qCWarning(scriptengine) << "ScriptEngine::waitTillDoneRunning called, but the script is on the same thread:" << getFilename();
        return;
    }
```

I added some prints...can someone send me their logs after they crash with this PR?

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-6c703a4-.tar_f2f676ff.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-6c703a4-_f2f676ff.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-6c703a4-.tar_f2f676ff.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-6c703a4-_f2f676ff.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-6c703a4-_f2f676ff.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-PR1054-6c703a4_f2f676ff.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1054/Vircadia-Quest-Alpha-PR1054-6c703a4_f2f676ff.apk

**Comment by SilverfishVR** [comment]
I have been running this quite a bit and while I did have 2 crashes none of them was when using the create menu which is generally where I crash the most so my general feeling is that it is more stable, definitely not worse and I did not see any new issues so that's good 👍 
Not making it worse is sort of a win right 😄 

one of my crash logs: 
[pr1054_CRASH.txt](https://github.com/vircadia/vircadia/files/6135321/pr1054_CRASH.txt)

**Comment by HifiExperiments** [comment]
hmmm wait which build was that with?  I’m not sure the first “fix” actually changed anything, and the latest commit is just additional logging to narrow down the issue, which doesn’t show in your logs.  I don’t feel great about this still, I think there’s something deeper happening that I don’t understand yet

**Comment by digisomni** [comment]
> 
> 
> hmmm wait which build was that with? I’m not sure the first “fix” actually changed anything, and the latest commit is just additional logging to narrow down the issue, which doesn’t show in your logs. I don’t feel great about this still, I think there’s something deeper happening that I don’t understand yet

Sir, you're distributing placebo builds.

**Comment by HifiExperiments** [comment]
only one of the builds was a placebo, the other was poison.

also gonna close this in favor of the asan/tsan investigation that should hopefully resolve the heap corruption that is causing this

**Pull request closed without merging**
