### PR TITLE
Fix up OSX package - prototyping

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e95b65f-_5a4fa90c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e95b65f-.tar_5a4fa90c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e95b65f-.tar_5a4fa90c.gz

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-e95b65f_5a4fa90c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e95b65f_5a4fa90c.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-105c785-.tar_abf8db9a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-105c785-.tar_abf8db9a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-105c785-_abf8db9a.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-105c785_abf8db9a.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-105c785_abf8db9a.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-105c785-_abf8db9a.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-45780ae-_610143f5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-45780ae-.tar_610143f5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-45780ae-.tar_610143f5.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-45780ae-_610143f5.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-45780ae-_610143f5.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-45780ae_610143f5.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-45780ae_610143f5.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-1e3e79f-_f5bb2a40.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-1e3e79f-.tar_f5bb2a40.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-1e3e79f-.tar_f5bb2a40.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-1e3e79f-_f5bb2a40.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-1e3e79f_f5bb2a40.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-1e3e79f_f5bb2a40.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e7e5fe6-.tar_37ea9f08.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e7e5fe6-.tar_37ea9f08.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e7e5fe6-_37ea9f08.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e7e5fe6-_37ea9f08.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e7e5fe6-_37ea9f08.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5f68874-.tar_92ed6239.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5f68874-.tar_92ed6239.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5f68874-_92ed6239.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5fcac1a-.tar_247d6490.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5fcac1a-.tar_247d6490.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5fcac1a-_247d6490.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5fcac1a-_247d6490.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5fcac1a_247d6490.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-5fcac1a_247d6490.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6413841-_e6076894.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6413841-.tar_e6076894.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6413841-.tar_e6076894.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6413841-_e6076894.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6413841-_e6076894.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6413841_e6076894.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-6413841_e6076894.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-12ccde9-.tar_82367790.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-12ccde9-_82367790.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-12ccde9-.tar_82367790.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-12ccde9-_82367790.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-12ccde9-_82367790.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-12ccde9_82367790.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-12ccde9_82367790.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e6ecfae-.tar_c3dd4dfb.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e6ecfae-.tar_c3dd4dfb.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e6ecfae-_c3dd4dfb.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e6ecfae-_c3dd4dfb.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-e6ecfae_c3dd4dfb.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-e6ecfae_c3dd4dfb.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5828d51-.tar_401c18e1.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5828d51-_401c18e1.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5828d51-.tar_401c18e1.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5828d51-_401c18e1.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5828d51-_401c18e1.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-5828d51_401c18e1.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-5828d51_401c18e1.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-863c1be-_282e2cc9.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-863c1be-.tar_282e2cc9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-863c1be-.tar_282e2cc9.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-863c1be-_282e2cc9.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-863c1be-_282e2cc9.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-863c1be_282e2cc9.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-863c1be_282e2cc9.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-915d1ca-.tar_b3a4c45a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-915d1ca-.tar_b3a4c45a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-915d1ca-_b3a4c45a.sh

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-915d1ca-_b3a4c45a.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-915d1ca-_b3a4c45a.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-915d1ca_b3a4c45a.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-915d1ca_b3a4c45a.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-75c272d-.tar_8ddefe25.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-75c272d-_8ddefe25.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-75c272d-.tar_8ddefe25.gz

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-75c272d-_8ddefe25.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-75c272d-_8ddefe25.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-75c272d_8ddefe25.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-75c272d_8ddefe25.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-.tar_deb086d8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-.tar_deb086d8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-_deb086d8.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-_deb086d8.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d_deb086d8.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-6c6480d_deb086d8.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-.tar_deb086d8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-.tar_deb086d8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-_deb086d8.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d_deb086d8.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-6c6480d_deb086d8.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-6c6480d-_deb086d8.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-73edbee-.tar_0abca869.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-73edbee-.tar_0abca869.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-73edbee-_0abca869.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-73edbee-_0abca869.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-Quest-Alpha-PR1075-73edbee_0abca869.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1075/Vircadia-PR1075-73edbee_0abca869.apk

**Comment by ctrlaltdavid** [comment]
Close in favour of https://github.com/vircadia/vircadia/pull/1086 .

**Pull request closed without merging**
