### PR TITLE
Try making OSX shut down scripts in the same manner as other OSes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd.tar_f4b0cd91.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd.tar_f4b0cd91.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-Quest-Alpha-PR1023-60f5ecd_f4b0cd91.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.apk

**Comment by ArcadeFever** [comment]
I could not get this OSX PR to crash upon exit like I could in 1032, so thats good, but I couldn't connect to any domains to try stressing out the loading of assets (I had to stick to serverless for my testing).

**Comment by Steve-Pruneau** [comment]
PR 1023 for macOS does not crash on Start or Quit. But it throws a protocol conflict for every domain that I try to visit through Explorer. So I wasn't really able to test it effectively.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd.tar_f4b0cd91.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd.tar_f4b0cd91.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-Quest-Alpha-PR1023-60f5ecd_f4b0cd91.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-60f5ecd_f4b0cd91.apk

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-2c9083b.tar_f4b0cd91.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-2c9083b_f4b0cd91.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-2c9083b.tar_f4b0cd91.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-2c9083b_f4b0cd91.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-2c9083b_f4b0cd91.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-Quest-Alpha-PR1023-2c9083b_f4b0cd91.apk

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1023/Vircadia-PR1023-2c9083b_f4b0cd91.dmg

**Comment by ctrlaltdavid** [comment]
Close in favour of https://github.com/vircadia/vircadia/pull/1064

**Pull request closed without merging**
