### PR TITLE
Add v1.0 of NyxUI with the "Entity Menu" feature

### PR DESCRIPTION
**Pull request by digisomni**
The entity menu offers property information about entities, sit controls for entities, and the ability for scripts to add actions to the menu for respective entities.

### To test...

**On desktop:** Press your left and right mouse buttons simultaneously on an entity.
**In VR:** Squeeze your controller **then** trigger on an entity while holding the grip.

### Known issues:

- When using the entity menu actions feature, there's not currently a way to update the values of the actions without re-registering the menu.

### Help

If you manage to set a weird configuration to trigger Nyx and you are unable to open it again, then do: `Settings` -> `Nyx` -> `Reset Entity Menu`.

If you want to disable the menu system entirely, you can disable it under `Settings` -> `Nyx` -> `Enable Entity Menu`.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-PR1107-7aecbc2-.tar_f2603e9a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-PR1107-7aecbc2-_f2603e9a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-PR1107-7aecbc2-.tar_f2603e9a.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-PR1107-7aecbc2-_f2603e9a.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-PR1107-7aecbc2-_f2603e9a.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-PR1107-7aecbc2_f2603e9a.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1107/Vircadia-Quest-Alpha-PR1107-7aecbc2_f2603e9a.apk

**Comment by vegaslon** [comment]
I VR mode menu pops up constantly when using things like push to talk, holding a mug, creating while talking etc

**Comment by digisomni** [comment]
How is push to talk normally triggered in VR?

**Comment by vegaslon** [comment]
using both grips at once is how push to talk is activated.

**Pull request closed without merging**
